### ISSUE TITLE
MS VS 2019 didn't work with this

### ISSUE THREAD

**Issue by pavelc7** [sciter-sdk/json-value-visualizer#1]
I go into .vsix as zip archive and
edit extension.vsixmanifest
set 17.0 version
 ```
<InstallationTarget Id="Microsoft.VisualStudio.Community" Version="[11.0,16.0]" /> 
  <InstallationTarget Id="Microsoft.VisualStudio.Pro" Version="[15.0,17.0]" /> 
```
installed in MSVS 2019. I can view in Installed Expansions
but it's not working;(
hm. it's not working in msvs 2017 either

**Comment by pravic** [comment]
Thanks, I'll check it.

**Comment by pravic** [comment]
>  it's not working in msvs 2017 either

True. VS 2017 warns that the extension is incompatible and when installed it doesn't work.

However, if you copy the sciter.natvis file [somewhere here](https://docs.microsoft.com/en-us/visualstudio/debugger/create-custom-views-of-native-objects?view=vs-2019#BKMK_natvis_location), it will work.

Could you check on VS 2019 by manually copying the natvis?

**Comment by pavelc7** [comment]
thanks,  %VSINSTALLDIR%\Common7\Packages\Debugger\Visualizers works for me for MS VS 2019

**Comment by pravic** [comment]
Interesting. I wonder, what's wrong with the vsixmanifest.

**Comment by pavelc7** [comment]
I need recheck it because it can be related with absence of json_value_pair in my sources as described in readme
Also you may add [how to check does it have errors](https://docs.microsoft.com/en-us/visualstudio/debugger/create-custom-views-of-native-objects?view=vs-2019#BKMK_Diagnosing_Natvis_errors) if it is not working to readme

**Comment by pavelc7** [comment]
So, i removed natvis from folder(that i mentioned above)
Install modified .vsix
It installed only next files
```
extension.vsixmanifest
favicon.ico
sciter-value.png
```
to 
c:\USERS\<username>\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_<some_random_letters>\EXTENSIONS\<more_random_letters>.BSE\
Then I run my code with&without json_value_pair and i've got
`Natvis: Fatal error: Can't open NATVIS-file "C\USERS\<username>\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_<some_random_letters>\EXTENSIONS\<more_random_letters>.BSE\sciter.natvis"`

I copyed sciter.natvis manually to that folder and it works
Thanks

**Comment by pavelc7** [comment]
Solution:
So I added next line
`<Default Extension="natvis" ContentType="text/xml" /> `
to `SciterValueVisualizer_modified.vsix\[Content_Types].xml` file
And .vsix intaller copyed sciter.natvis to folder of extension automatically

**Comment by pravic** [comment]
Interesting. Thanks for the help!

**Comment by pravic** [comment]
Could you check [this VSIX](https://github.com/sciter-sdk/json-value-visualizer/releases/download/v1.0.2/SciterValueVisualizer.vsix)?

**Comment by pravic** [comment]
I can't update this extension on Marketplace due to an obscure error message:

> Error: This extension targets Visual Studio 2017 but was not built with an up-to-date VSSDK.

These didn't help:

https://devblogs.microsoft.com/visualstudio/how-to-upgrade-extensions-to-support-visual-studio-2019/
https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-migrate-extensibility-projects-to-visual-studio-2017?view=vs-2017
http://www.visualstudioextensibility.com/2017/01/10/its-time-to-change-the-vsix-manifest-of-your-extension-to-v3-for-visual-studio-2017-compatibility/

If I add a prerequisites section, it fails with

> Error: The file is not a valid VSIX file.

**Comment by pavelc7** [comment]
did you add exactly "[15.0,16.0)" in Prerequisite?
maybe for v2 extension you need set InstallationTarget  to upper then "[11.0", to "[14." or "[15,"
```
  <Prerequisite Id="Microsoft.VisualStudio.Component.CoreEditor" Version="[15.0,16.0)" DisplayName="Visual Studio core editor" /> 
 <InstallationTarget Id="Microsoft.VisualStudio.Pro" Version="[14.0,17.0)" />
```
p.s. I will try vsix later today

**Comment by pravic** [comment]
Yeah, I've tried different combinations, no luck.

**Comment by pavelc7** [comment]
i downloaded vsix. removed plugin/installed it. it works

**Comment by pravic** [comment]
Okay, thanks.

The update issue goes to its own ticket #4.
